[package]
name = "llmsafeguarding"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
csv = "1.3.0"
dotenvy = "0.15.7"
genai = "=0.1.2"
tokio = { version = "1.38.0", features = ["full"] }
